[2024-11-28 20:01:29|24980|INFO|base_model.py:91]  session [2850664376176] and [user] has an operator: QUERY.
[2024-11-28 20:01:36|26284|INFO|base_model.py:91]  session [2850664377376] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:01:36|26284|INFO|sales_view.py:31]  Regress Predict init successfully
[2024-11-28 20:01:36|25464|INFO|base_model.py:91]  session [2850664373872] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:01:36|25464|INFO|sales_view.py:31]  Regress Predict init successfully
[2024-11-28 20:02:42|28396|INFO|base_model.py:91]  session [2850664374400] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:02:42|28396|INFO|sales_view.py:31]  Regress Predict init successfully
[2024-11-28 20:02:49|16536|INFO|sales_view.py:44]  使用长短时记忆网络预测2024/01~2024/11的汽车销量情况
[2024-11-28 20:02:49|16536|ERROR|db_connection.py:53]  [Except]transaction function error, info is File not found: filepath=D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\model\sales_lstm1.keras. Please ensure the file is an accessible `.keras` zip file.
[2024-11-28 20:02:49|16536|ERROR|db_connection.py:54]  Traceback (most recent call last):
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\database\db_connection.py", line 44, in wrapper
    res = func(*args, **kwargs)
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\views\sales_view.py", line 46, in sales_regress
    res_dict = predict(method, start, end)
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\sales_predict.py", line 23, in predict
    model = LSTMRegressionPredict()
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\lstm_regress.py", line 15, in __init__
    self.model = load_model(f'{model_path}.keras')  # 加载模型
  File "D:\ruanjian\Python\Python310\lib\site-packages\keras\src\saving\saving_api.py", line 200, in load_model
    raise ValueError(
ValueError: File not found: filepath=D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\model\sales_lstm1.keras. Please ensure the file is an accessible `.keras` zip file.

[2024-11-28 20:02:49|16536|ERROR|__init__.py:117]  load_model error, info is File not found: filepath=D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\model\sales_lstm1.keras. Please ensure the file is an accessible `.keras` zip file.
[2024-11-28 20:02:49|16536|ERROR|__init__.py:118]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\database\db_connection.py", line 56, in wrapper
    raise e
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\database\db_connection.py", line 44, in wrapper
    res = func(*args, **kwargs)
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\views\sales_view.py", line 46, in sales_regress
    res_dict = predict(method, start, end)
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\sales_predict.py", line 23, in predict
    model = LSTMRegressionPredict()
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\lstm_regress.py", line 15, in __init__
    self.model = load_model(f'{model_path}.keras')  # 加载模型
  File "D:\ruanjian\Python\Python310\lib\site-packages\keras\src\saving\saving_api.py", line 200, in load_model
    raise ValueError(
ValueError: File not found: filepath=D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\model\sales_lstm1.keras. Please ensure the file is an accessible `.keras` zip file.

[2024-11-28 20:04:21|27048|INFO|base_model.py:91]  session [2850665499280] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:04:21|27048|INFO|sales_view.py:31]  Regress Predict init successfully
[2024-11-28 20:04:27|27744|INFO|sales_view.py:44]  使用长短时记忆网络预测2024/01~2024/11的汽车销量情况
[2024-11-28 20:04:28|27744|ERROR|db_connection.py:53]  [Except]transaction function error, info is [Errno 2] No such file or directory: 'D:\\py_learn\\learn\\LogisticsDesign\\LogisticsDesign\\business\\sales\\data\\sales_data.xlsx'
[2024-11-28 20:04:28|27744|ERROR|db_connection.py:54]  Traceback (most recent call last):
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\database\db_connection.py", line 44, in wrapper
    res = func(*args, **kwargs)
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\views\sales_view.py", line 46, in sales_regress
    res_dict = predict(method, start, end)
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\sales_predict.py", line 23, in predict
    model = LSTMRegressionPredict()
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\lstm_regress.py", line 17, in __init__
    df = pd.read_excel(file_path, engine='openpyxl')  # 加载数据
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\excel\_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\excel\_openpyxl.py", line 553, in __init__
    super().__init__(
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\excel\_base.py", line 563, in __init__
    self.handles = get_handle(
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\py_learn\\learn\\LogisticsDesign\\LogisticsDesign\\business\\sales\\data\\sales_data.xlsx'

[2024-11-28 20:04:28|27744|ERROR|__init__.py:117]  get_handle error, info is [Errno 2] No such file or directory: 'D:\\py_learn\\learn\\LogisticsDesign\\LogisticsDesign\\business\\sales\\data\\sales_data.xlsx'
[2024-11-28 20:04:28|27744|ERROR|__init__.py:118]  Traceback (most recent call last):
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ruanjian\Python\Python310\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\database\db_connection.py", line 56, in wrapper
    raise e
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\database\db_connection.py", line 44, in wrapper
    res = func(*args, **kwargs)
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\back_end\views\sales_view.py", line 46, in sales_regress
    res_dict = predict(method, start, end)
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\sales_predict.py", line 23, in predict
    model = LSTMRegressionPredict()
  File "D:\py_learn\learn\LogisticsDesign\LogisticsDesign\business\sales\lstm_regress.py", line 17, in __init__
    df = pd.read_excel(file_path, engine='openpyxl')  # 加载数据
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\excel\_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\excel\_openpyxl.py", line 553, in __init__
    super().__init__(
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\excel\_base.py", line 563, in __init__
    self.handles = get_handle(
  File "D:\ruanjian\Python\Python310\lib\site-packages\pandas\io\common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\py_learn\\learn\\LogisticsDesign\\LogisticsDesign\\business\\sales\\data\\sales_data.xlsx'

[2024-11-28 20:06:09|24336|INFO|base_model.py:91]  session [2179674351040] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:06:09|2072|INFO|base_model.py:91]  session [2179674355312] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:06:09|24336|INFO|sales_view.py:31]  Regress Predict init successfully
[2024-11-28 20:06:09|2072|INFO|sales_view.py:31]  Regress Predict init successfully
[2024-11-28 20:06:13|22896|INFO|sales_view.py:44]  使用长短时记忆网络预测2024/01~2024/10的汽车销量情况
[2024-11-28 20:06:15|22896|INFO|base_model.py:32]  session [2179674356320] and [RegressPredict] has an operator: ADD.
[2024-11-28 20:06:15|22896|INFO|base_model.py:91]  session [2179674356320] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:06:16|22896|INFO|sales_view.py:56]  Regress Predict successfully
[2024-11-28 20:08:37|7332|INFO|sales_view.py:44]  使用长短时记忆网络预测2024/01~2024/10的汽车销量情况
[2024-11-28 20:08:39|7332|INFO|base_model.py:32]  session [2426871752272] and [RegressPredict] has an operator: ADD.
[2024-11-28 20:08:39|7332|INFO|base_model.py:91]  session [2426871752272] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:08:39|7332|INFO|sales_view.py:56]  Regress Predict successfully
[2024-11-28 20:09:03|24252|INFO|base_model.py:91]  session [2426871752656] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:09:03|24252|INFO|sales_view.py:31]  Regress Predict init successfully
[2024-11-28 20:09:09|24800|INFO|sales_view.py:44]  使用长短时记忆网络预测2024/05~2024/07的汽车销量情况
[2024-11-28 20:09:10|24800|INFO|base_model.py:32]  session [2426896385360] and [RegressPredict] has an operator: ADD.
[2024-11-28 20:09:10|24800|INFO|base_model.py:91]  session [2426896385360] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:09:10|24800|INFO|sales_view.py:56]  Regress Predict successfully
[2024-11-28 20:09:39|26520|INFO|sales_view.py:44]  使用长短时记忆网络预测2024/01~2024/12的汽车销量情况
[2024-11-28 20:09:41|26520|INFO|base_model.py:32]  session [2426896299392] and [RegressPredict] has an operator: ADD.
[2024-11-28 20:09:41|26520|INFO|base_model.py:91]  session [2426896299392] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:09:41|26520|INFO|sales_view.py:56]  Regress Predict successfully
[2024-11-28 20:09:52|24580|INFO|sales_view.py:44]  使用线性回归预测2024/01~2024/12的汽车销量情况
[2024-11-28 20:09:52|24580|INFO|base_model.py:32]  session [2426897688672] and [RegressPredict] has an operator: ADD.
[2024-11-28 20:09:52|24580|INFO|base_model.py:91]  session [2426897688672] and [RegressPredict] has an operator: QUERY.
[2024-11-28 20:09:52|24580|INFO|sales_view.py:56]  Regress Predict successfully
